import type { AccountNode, AccountRole, AnalysisResult, MoneyFlowEdge, RiskLevel, Transaction } from "@/types/aml";
const level = (score: number): RiskLevel => score >= 65 ? "high" : score >= 35 ? "medium" : "low";
const round = (value: number): number => Math.round(value * 100) / 100;
export function analyzeTransactions(transactions: Transaction[]): AnalysisResult {
  const map = new Map<string, { inflow: number; outflow: number; inCount: number; outCount: number; senders: Set<string>; receivers: Set<string> }>();
  const ensure = (id: string) => { const existing = map.get(id); if (existing) return existing; const created = { inflow: 0, outflow: 0, inCount: 0, outCount: 0, senders: new Set<string>(), receivers: new Set<string>() }; map.set(id, created); return created; };
  const edgesByKey = new Map<string, MoneyFlowEdge>(); const sorted = [...transactions].sort((a, b) => Date.parse(a.timestamp) - Date.parse(b.timestamp));
  for (const transaction of sorted) { const sender = ensure(transaction.sender); const receiver = ensure(transaction.receiver); sender.outflow += transaction.amount; sender.outCount += 1; sender.receivers.add(transaction.receiver); receiver.inflow += transaction.amount; receiver.inCount += 1; receiver.senders.add(transaction.sender); const key = `${transaction.sender}->${transaction.receiver}`; const edge = edgesByKey.get(key); if (edge) { edge.amount += transaction.amount; edge.transactionIds.push(transaction.id); } else edgesByKey.set(key, { id: `edge-${edgesByKey.size}`, source: transaction.sender, target: transaction.receiver, amount: transaction.amount, timestamp: transaction.timestamp, transactionIds: [transaction.id] }); }
  const maxVolume = Math.max(...[...map.values()].map((v) => v.inflow + v.outflow), 1);
  const accounts: AccountNode[] = [...map.entries()].map(([id, metrics]) => { const totalVolume = metrics.inflow + metrics.outflow; const factors: string[] = []; let score = 0; if (metrics.senders.size >= 4) { score += Math.min(20, metrics.senders.size * 4); factors.push("Получает средства от большого числа уникальных отправителей"); } if (metrics.receivers.size >= 3) { score += Math.min(15, metrics.receivers.size * 3); factors.push("Распределяет средства между несколькими получателями"); } const incoming = sorted.filter((t) => t.receiver === id); const outgoing = sorted.filter((t) => t.sender === id); const transit = incoming.some((input) => outgoing.some((output) => Date.parse(output.timestamp) >= Date.parse(input.timestamp) && Date.parse(output.timestamp) - Date.parse(input.timestamp) <= 3600000 && output.amount >= input.amount * 0.65)); if (transit) { score += 20; factors.push("Быстро переводит значительную часть входящих средств дальше"); } if (totalVolume >= maxVolume * 0.65) { score += 15; factors.push("Имеет высокий оборот относительно других счетов"); } const cycle = sorted.some((t) => t.sender === id && sorted.some((next) => next.sender === t.receiver && next.receiver === id)); if (cycle) { score += 15; factors.push("Участвует в замкнутом маршруте переводов"); } const bySender = sorted.filter((t) => t.sender === id); const split = bySender.some((first, index) => bySender.slice(index + 1).filter((next) => Math.abs(Date.parse(next.timestamp) - Date.parse(first.timestamp)) <= 86400000 && Math.abs(next.amount - first.amount) / first.amount <= 0.12).length >= 2); if (split) { score += 15; factors.push("Делит платежи на несколько близких по размеру переводов"); } const role: AccountRole = factors.length >= 3 ? "suspicious_intermediary" : totalVolume >= maxVolume * 0.65 && metrics.senders.size + metrics.receivers.size >= 5 ? "hub" : metrics.senders.size >= 4 ? "collector" : metrics.receivers.size >= 3 ? "distributor" : transit ? "transit" : metrics.outflow > metrics.inflow * 2 ? "source" : metrics.inflow > metrics.outflow * 2 ? "receiver" : "unknown"; return { id, label: id, inflow: round(metrics.inflow), outflow: round(metrics.outflow), totalVolume: round(totalVolume), inCount: metrics.inCount, outCount: metrics.outCount, uniqueSenders: metrics.senders.size, uniqueReceivers: metrics.receivers.size, role, riskScore: Math.min(100, score), riskLevel: level(score), riskFactors: factors.length ? factors : ["Явных риск-сигналов не обнаружено"] }; }).sort((a, b) => b.riskScore - a.riskScore);
  return { transactions: sorted, accounts, edges: [...edgesByKey.values()], suspiciousAccounts: accounts.filter((a) => a.riskScore > 0).slice(0, 10), totalVolume: round(transactions.reduce((sum, t) => sum + t.amount, 0)) };
}
export function neighborhood(result: AnalysisResult, root: string, depth: number): { nodes: Set<string>; edges: MoneyFlowEdge[] } { const nodes = new Set([root]); let frontier = new Set([root]); for (let step = 0; step < depth; step += 1) { const next = new Set<string>(); for (const edge of result.edges) if (frontier.has(edge.source) || frontier.has(edge.target)) { nodes.add(edge.source); nodes.add(edge.target); next.add(edge.source); next.add(edge.target); } frontier = next; } return { nodes, edges: result.edges.filter((edge) => nodes.has(edge.source) && nodes.has(edge.target)) }; }
