"use client";
import { useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowDownToLine, CheckCircle2, Database, FileUp, Focus, Gauge, Network, RefreshCw, Search, ShieldAlert, Sparkles, Upload, Users } from "lucide-react";
import MoneyFlowGraph from "@/components/money-flow-graph";
import { analyzeTransactions } from "@/lib/analysis";
import { demoTransactions } from "@/lib/demo-data";
import { parseCsv } from "@/lib/validation";
import { aiAnalysisSchema } from "@/lib/ai-schema";
import { buildAiProfile } from "@/lib/ai-profile";
import { createFallbackAnalysis } from "@/lib/ai-fallback";
import type { AccountNode, AnalysisResult, Transaction } from "@/types/aml";
import type { AiAnalysisResult } from "@/types/ai";
import "./page.css";

const money = (amount: number): string => `${new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 0 }).format(amount)} ₸`;
const date = (value: string): string => new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const roleName = (role: AccountNode["role"]): string => ({ source: "Источник", receiver: "Получатель", transit: "Транзит", collector: "Сборщик", distributor: "Распределитель", hub: "Хаб", suspicious_intermediary: "Подозрительный посредник", unknown: "Не определена" })[role];
const riskLabel = (level: AccountNode["riskLevel"]): string => ({ low: "Низкий", medium: "Средний", high: "Высокий" })[level];

export default function Home() {
  const [result, setResult] = useState<AnalysisResult | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null); const [depth, setDepth] = useState(4); const [focusMode, setFocusMode] = useState(false); const [gidQuery, setGidQuery] = useState(""); const [message, setMessage] = useState<{ type: "error" | "success"; text: string } | null>(null); const [loading, setLoading] = useState(false); const [aiLoading, setAiLoading] = useState(false); const [aiAnalysis, setAiAnalysis] = useState<AiAnalysisResult | null>(null); const [aiError, setAiError] = useState<string | null>(null); const fileRef = useRef<HTMLInputElement>(null);
  const selected = useMemo(() => result?.accounts.find((account) => account.id === selectedId) ?? result?.accounts[0] ?? null, [result, selectedId]);
  const load = (transactions: Transaction[], success: string) => { const analysis = analyzeTransactions(transactions); setResult(analysis); setSelectedId(analysis.accounts[0]?.id ?? null); setFocusMode(false); setAiAnalysis(null); setAiError(null); setMessage({ type: "success", text: success }); };
  const selectAccount = (id: string) => { if (id !== selectedId) { setAiAnalysis(null); setAiError(null); } setSelectedId(id); };
  const findGid = () => { const query = gidQuery.trim(); const account = result?.accounts.find((candidate) => candidate.id === query); if (!account) { setMessage({ type: "error", text: query ? `Узел ${query} не найден в загруженных данных.` : "Введите gid для поиска." }); return; } selectAccount(account.id); setFocusMode(true); setMessage({ type: "success", text: `Найден узел ${account.id}.` }); };
  const onFile = async (file: File | undefined) => { if (!file) return; setLoading(true); setMessage(null); try { load(await parseCsv(file), `Загружено транзакций: ${file.name}`); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Не удалось обработать файл." }); } finally { setLoading(false); } };
  const onAiAnalyze = async () => { if (!result || !selected) return; const profile = buildAiProfile(result, selected.id); if (!profile) return; setAiLoading(true); setAiError(null); try { const response = await fetch("/api/ai-analysis", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ profile }) }); const body: unknown = await response.json(); if (!response.ok) { const errorBody = body as { error?: unknown }; throw new Error(typeof errorBody.error === "string" ? errorBody.error : "AI-анализ недоступен."); } const parsed = aiAnalysisSchema.safeParse(body); if (!parsed.success) throw new Error("AI вернул результат в неожиданном формате."); setAiAnalysis(parsed.data); } catch (error) { setAiError(error instanceof Error ? error.message : "AI-анализ недоступен."); setAiAnalysis(createFallbackAnalysis(selected)); } finally { setAiLoading(false); } };
  const highRisk = result?.accounts.filter((account) => account.riskLevel === "high").length ?? 0;
  return <main className="shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Network size={21} /></div><div><h1>Cifron <span>AI</span></h1><p>Интеллектуальная карта движения денег для AML-аналитика</p></div></div><div className="status"><span className="pulse" /> Локальный анализ данных</div></header>
    <div className="disclaimer"><ShieldAlert size={18} /> Cifron AI — вспомогательный аналитический инструмент. Результаты не подтверждают факт нарушения и требуют проверки AML-специалистом.</div>
    <section className="toolbar"><div><h2>Панель расследования</h2><p>Найдите цепочки, роли и приоритеты проверки в одном экране.</p></div><div className="actions"><form className="gid-search" onSubmit={(event) => { event.preventDefault(); findGid(); }}><Search size={15} /><input value={gidQuery} onChange={(event) => setGidQuery(event.target.value)} placeholder="Поиск gid" aria-label="Поиск по gid" /><button className="button secondary" type="submit">Найти</button></form><button className="button secondary" onClick={() => fileRef.current?.click()} aria-label="Загрузить CSV"><Upload size={16} /> Загрузить CSV</button><button className="button primary" onClick={() => load(demoTransactions, "Демо-сценарий загружен: 37 транзакций") } aria-label="Загрузить демонстрационный сценарий"><Database size={16} /> Загрузить демо-сценарий</button><input ref={fileRef} type="file" accept=".csv,text/csv" hidden onChange={(event) => void onFile(event.target.files?.[0])} /></div></section>
    <section className="upload-hint"><FileUp size={18} /><div><strong>Загрузите историю переводов</strong><span>UTF-8 CSV · до 5 МБ · обязательные поля: transaction_id, timestamp, sender, receiver, amount</span></div>{loading && <span className="loading">Анализируем…</span>}</section>
    {message && <div className={`message ${message.type}`}>{message.type === "error" ? <AlertTriangle size={17} /> : <CheckCircle2 size={17} />}{message.text}</div>}
    <section className="stats"><Stat icon={<ArrowDownToLine />} label="Транзакций" value={String(result?.transactions.length ?? 0)} /><Stat icon={<Users />} label="Счетов в графе" value={String(result?.accounts.length ?? 0)} /><Stat icon={<Gauge />} label="Общий оборот" value={money(result?.totalVolume ?? 0)} /><Stat icon={<ShieldAlert />} label="Высокий риск" value={String(highRisk)} accent={highRisk > 0} /></section>
    <section className="workspace"><div className="panel graph-panel"><div className="panel-heading"><div><h3>Карта движения денег</h3><p>{focusMode ? `Фокус на ${selected?.label ?? "выбранном узле"} · связанные узлы до ${depth} уровня` : "Кликните по узлу, чтобы открыть детали. Толщина стрелки отражает сумму."}</p></div><label className="depth">Глубина <select value={depth} onChange={(event) => setDepth(Number(event.target.value))} aria-label="Глубина графа">{[1,2,3,4].map((value) => <option key={value} value={value}>{value} уровня</option>)}</select></label></div><MoneyFlowGraph result={result} selectedId={selected?.id ?? null} depth={depth} focusId={selected?.id ?? null} focusMode={focusMode} onSelect={selectAccount} /></div>
      <aside className="side-stack"><NodeDetails account={selected} focusMode={focusMode} aiAnalysis={aiAnalysis} aiError={aiError} aiLoading={aiLoading} onToggleFocus={() => setFocusMode((current) => !current)} onAiAnalyze={onAiAnalyze} /><PriorityList accounts={result?.suspiciousAccounts ?? []} onSelect={selectAccount} /></aside></section>
    <section className="panel transactions"><div className="panel-heading"><div><h3>Последние транзакции</h3><p>Показаны последние 50 операций из загруженного набора.</p></div><span className="count-pill">{result?.transactions.length ?? 0} всего</span></div><TransactionTable rows={result?.transactions.slice(-50).reverse() ?? []} /></section>
    <footer>Cifron AI · MVP HackAlem AI · Анализ выполняется локально в браузере</footer>
  </main>;
}
function Stat({ icon, label, value, accent = false }: { icon: React.ReactNode; label: string; value: string; accent?: boolean }) { return <div className={`stat ${accent ? "accent" : ""}`}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>; }
function NodeDetails({ account, focusMode, aiAnalysis, aiError, aiLoading, onToggleFocus, onAiAnalyze }: { account: AccountNode | null; focusMode: boolean; aiAnalysis: AiAnalysisResult | null; aiError: string | null; aiLoading: boolean; onToggleFocus: () => void; onAiAnalyze: () => void }) { if (!account) return <div className="panel empty-side"><Network size={24} /><h3>Детали узла</h3><p>Выберите узел на графе после загрузки данных.</p></div>; return <div className="panel node-details"><div className="panel-heading"><div><span className="eyebrow">Выбранный узел</span><h3>{account.label}</h3></div><span className={`risk-badge ${account.riskLevel}`}>{account.riskScore} · {riskLabel(account.riskLevel)}</span></div><div className="role-chip">{roleName(account.role)}</div><div className="node-actions"><button className={`node-action ${focusMode ? "active" : ""}`} onClick={onToggleFocus} aria-label={focusMode ? "Вернуться к полному графу" : "Включить фокус на выбранном узле"}><Focus size={14} />{focusMode ? "Полный граф" : "Фокус на узле"}</button><button className="node-action ai" onClick={onAiAnalyze} disabled={aiLoading} aria-label="AI-анализ узла"><Sparkles size={14} />{aiLoading ? "Анализируем…" : "AI-анализ узла"}</button></div><div className="metrics"><Metric label="Входящий объём" value={money(account.inflow)} /><Metric label="Исходящий объём" value={money(account.outflow)} /><Metric label="Отправителей" value={String(account.uniqueSenders)} /><Metric label="Получателей" value={String(account.uniqueReceivers)} /></div><h4>Факторы риска</h4><ul className="factor-list">{account.riskFactors.map((factor) => <li key={factor}><span />{factor}</li>)}</ul>{aiLoading && <div className="ai-loading"><Sparkles size={15} />Анализируем профиль узла…</div>}{aiError && <div className="ai-error"><span>{aiError}</span><button className="retry-button" onClick={onAiAnalyze}><RefreshCw size={13} />Повторить</button></div>}{aiAnalysis && <AiAnalysisCard analysis={aiAnalysis} fallback={Boolean(aiError)} />}</div>; }
function AiAnalysisCard({ analysis, fallback }: { analysis: AiAnalysisResult; fallback: boolean }) { return <section className={`ai-card ${fallback ? "fallback" : ""}`}><div className="ai-card-title"><Sparkles size={15} /><strong>{fallback ? "Локальный fallback-анализ" : "AI-заключение"}</strong></div><div className="ai-section"><span>Объяснение роли</span><p>{analysis.roleExplanation}</p></div><div className="ai-section"><span>Краткий вывод</span><p>{analysis.riskSummary}</p></div><div className="ai-section"><span>Риск-сигналы</span><ul>{analysis.keySignals.map((signal) => <li key={signal}>{signal}</li>)}</ul></div><div className="ai-section"><span>Рекомендуемые проверки</span><ul>{analysis.recommendedChecks.map((check) => <li key={check}>{check}</li>)}</ul></div><small>{analysis.disclaimer}</small></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function PriorityList({ accounts, onSelect }: { accounts: AccountNode[]; onSelect: (id: string) => void }) { return <div className="panel priority"><div className="panel-heading"><div><h3>Кого проверить первым</h3><p>Рейтинг по объяснимому risk score</p></div><span className="count-pill">топ-{Math.min(accounts.length, 10)}</span></div>{accounts.length ? <div className="priority-list">{accounts.slice(0, 10).map((account, index) => <button key={account.id} className="priority-row" onClick={() => onSelect(account.id)}><b>{String(index + 1).padStart(2, "0")}</b><span className="priority-main"><strong>{account.label}</strong><small>{roleName(account.role)}</small></span><span className={`score ${account.riskLevel}`}>{account.riskScore}</span></button>)}</div> : <div className="empty-mini">После анализа здесь появится список приоритетных счетов.</div>}</div>; }
function TransactionTable({ rows }: { rows: Transaction[] }) { return rows.length ? <div className="table-scroll"><table><thead><tr><th>Время</th><th>Отправитель</th><th>Получатель</th><th>Сумма</th><th>Комментарий</th></tr></thead><tbody>{rows.map((transaction) => <tr key={transaction.id}><td>{date(transaction.timestamp)}</td><td>{transaction.sender}</td><td>{transaction.receiver}</td><td className="amount">{money(transaction.amount)}</td><td>{transaction.comment || "—"}</td></tr>)}</tbody></table></div> : <div className="table-empty"><ArrowDownToLine size={22} />Здесь появятся операции после загрузки файла.</div>; }
